# Generated by Django 3.2.2 on 2021-05-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('host', 'host'), ('guest', 'guest'), ('observer', 'observer')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('passcode', models.CharField(max_length=10, null=True)),
                ('link', models.CharField(max_length=11)),
                ('users', models.ManyToManyField(to='VideoConfApp.Contact')),
            ],
        ),
    ]
