# Generated by Django 3.2.3 on 2021-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoConfApp', '0002_auto_20210514_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
